### ISSUE TITLE
起動時にNPEが出るので対応する

### ISSUE THREAD

**Issue by sakai-y** [its-succ/dakoku#33]
```
./gradlew appengineRun
2018-06-20 20:15:45.890:INFO::main: Logging initialized @1390ms
6 20, 2018 11:15:46 午前 com.google.appengine.tools.development.IsolatedAppClassLoader checkWorkingDirectory
警告: Your working directory, (/Users/mihonakamoto/daken) is not equal to your 
web application root (/Users/mihonakamoto/daken/build/exploded-daken)
You will not be able to access files from your working directory on the production server.

2018-06-20 20:15:46.826:INFO:oejs.Server:main: jetty-9.3.18.v20170406
2018-06-20 20:15:48.560:WARN:oeja.ClassInheritanceHandler:qtp1014328909-16: 
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
        at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
2018-06-20 20:15:51.258:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=4070ms
```
https://stackoverflow.com/questions/50667168/run-spring-boot-webapp-using-appenginerun/50695564

**Comment by sakai-y** [comment]
GAE SDK付属のDevAppServerがJetty9.3.18を使ってて、これがSpringBoot2.x（Java9対応）に対応できていないようだ。
https://issuetracker.google.com/issues/65200034 で議論されているが、Jetty9.4なら解消されることは認識されている。
SDKのアップデートを待つか、SpringBoot1.5.xにするか、どっちか。
＃SpringBoot1.5.xにすればNPEが発生しないことは確認した

SpringBoot1.xにするとWebFluxが使えないが・・・。
